name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: './src/AIGame/AIGame.sln'
      PROJECT: './src/AIGame/AIGame.Models/AIGame.Models.csproj'
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Build Version
        run: |
          $Date =  Get-Date -format "yyyy-MM-dd"
          $BuildNumber = $GITHUB_RUN_NUMBER
          echo "BUILD_VERSION=$Date.$BuildNumber" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        shell: pwsh

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $PROJECT

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x

      - name: Build
        run: dotnet build $PROJECT --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

      - name: Publish
        run: nuget push **\*.nupkg -Source 'https://www.myget.org/F/daniel/api/v2/package' -ApiKey ${{secrets.MYGET_API_KEY}}
